behaviors:
  MultirotorAgent:
    trainer_type: sac

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 256
      buffer_size: 1000000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      
      # SAC-specific hyperparameters
      buffer_init_steps: 0
      tau: 0.005
      init_entcoef: 1.0
      save_replay_buffer: false

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 256
      num_layers: 2
    
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      
    threaded: true
    max_steps: 200000000
    time_horizon: 200
    summary_freq: 1000
